options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  leading-zero: 0
  no-color-literals: 0
  nesting-depth: 0
  no-qualifying-elements: 0
  no-transition-all: 0
  no-vendor-prefixes: 0